-- ===== Tabla de Roles =====
CREATE TABLE IF NOT EXISTS rol (
  id_rol    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre    VARCHAR(60)  NOT NULL,
  descripcion VARCHAR(255)
);

-- ===== Tabla de Usuarios =====
CREATE TABLE IF NOT EXISTS usuario (
  id_usuario          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre              VARCHAR(120) NOT NULL,
  apellido            VARCHAR(120) NOT NULL,
  email               VARCHAR(255) NOT NULL,
  documento_identidad VARCHAR(50),
  fecha_nacimiento    DATE,
  direccion           VARCHAR(255),
  telefono            VARCHAR(50),
  salario_base        NUMERIC(18,2) NOT NULL,
  id_rol              BIGINT,
  CONSTRAINT uq_usuario_email UNIQUE (email),
  CONSTRAINT fk_usuario_rol
    FOREIGN KEY (id_rol)
    REFERENCES rol (id_rol)
    ON UPDATE NO ACTION
    ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_usuario_id_rol ON usuario(id_rol);