-- ===== Tabla de Roles =====
CREATE TABLE IF NOT EXISTS rol (
  id_rol    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre    VARCHAR(60)  NOT NULL,
  descripcion VARCHAR(255),
  CONSTRAINT uq_rol_nombre UNIQUE (nombre)
);

-- ===== Tabla de Usuarios =====
CREATE TABLE IF NOT EXISTS usuario (
  id_usuario          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre              VARCHAR(120) NOT NULL,
  apellido            VARCHAR(120) NOT NULL,
  email               VARCHAR(255) NOT NULL,
  contrasena          VARCHAR(255),
  documento_identidad VARCHAR(50),
  fecha_nacimiento    DATE,
  direccion           VARCHAR(255),
  telefono            VARCHAR(50),
  salario_base        NUMERIC(18,2) NOT NULL,
  id_rol              BIGINT,
  CONSTRAINT uq_usuario_email UNIQUE (email),
  CONSTRAINT fk_usuario_rol
    FOREIGN KEY (id_rol)
    REFERENCES rol (id_rol)
    ON UPDATE NO ACTION
    ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_usuario_id_rol ON usuario(id_rol);

INSERT INTO rol (nombre, descripcion) VALUES
  ('ADMIN',   'Administrador del sistema'),
  ('ASESOR',  'Analiza y gestiona solicitudes'),
  ('CLIENTE', 'Solicitante de préstamo')
ON CONFLICT (nombre) DO UPDATE
SET descripcion = EXCLUDED.descripcion;

--INSERT INTO usuario (nombre, apellido, email, contrasena, salario_base, id_rol)
--SELECT 'Admin', 'Root', 'admin@crediya.pe',
--'$2a$10$REEMPLAZA_ESTE_HASH_BCRYPT...', 0,
--r.id_rol
--FROM rol r
--WHERE r.nombre = 'ADMIN'
--ON CONFLICT DO NOTHING;

COMMIT;