services:
  postgres:
    image: postgres:16-alpine
    container_name: crediya-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d  # ejecuta *.sql al primer arranque
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - crediya-net

  pgadmin:
    image: dpage/pgadmin4:latest  # opcional; puedes usar DBeaver si prefieres
    container_name: crediya-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - crediya-net

volumes:
  pgdata:

networks:
  crediya-net: